version: 2.1

orbs:
  codecov: codecov/codecov@3.1.1

jobs:
  test:
    docker:
      - image: circleci/python:3.9.2-node-browsers-legacy
    steps:
      - checkout
      - run:
          command: |
            poetry install
      - run:
          command: |
            poetry run python -m pytest -v --cov=markdownusm --cov-report=xml --capture=no -k "not integration"
      - codecov/upload:
          file: ./coverage.xml

  upload-testpypi:
    docker:
      - image: circleci/python:3.9.2-node-browsers-legacy
    steps:
      - checkout
      - run:
          command: |
            poetry config repositories.testpypi https://test.pypi.org/legacy/
            poetry config pypi-token.testpypi "${TEST_PYPI_TOKEN}"
            poetry publish --build -r testpypi

  upload-pypi:
    docker:
      - image: circleci/python:3.9.2-node-browsers-legacy
    steps:
      - checkout
      - run:
          command: |
            poetry config pypi-token.pypi "${PYPI_TOKEN}"
            poetry publish --build

workflows:
  version: 2
  test:
    jobs:
      - test
      - upload-testpypi:
          requires:
            - test
          filters:
            branches:
              only:
                develop
      - upload-pypi:
          requires:
            - test
          filters:
            branches:
              only:
                main
